name: google_place_plus
description: A new Flutter package for handle google place api that place search and details and photos and autocomplete and query autocomplete requests are available
version: 1.0.0
homepage: https://github.com/ijashuzain/google_place_plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
